#!/usr/bin/env bash

if [[ -f /etc/spm.conf ]]
then
	source /etc/spm.conf
fi

if [[ -z $STORAGE_FOLDER ]]; then STORAGE_FOLDER=$HOME/.spm_storage; fi
VERSION=0.8

cmd_help(){
	cat <<-_EOF
	Usage:
	  spm [command]
	Commands:
	  help, --help, -h      print this message
	  init                  initialize spm storage
	  ls                    show all encrypted files
	  enc [file]            encrypt new file
	  dec [file]            decrypt encrypted file
	  rm [file]             remove encrypted file
	  edit [file]           edit existing encrypted file
	  version               print spm version
	_EOF
}

cmd_init(){
	if [[ -d $STORAGE_FOLDER ]]
	then
		echo "SPM storage already exists in $STORAGE_FOLDER"
	else
		mkdir -p $STORAGE_FOLDER
		echo "SPM storage initialized in $STORAGE_FOLDER"
	fi
}

cmd_ls(){
	if [[ -d $STORAGE_FOLDER ]]
	then
		echo "SPM storage:"
		# ls -1 $STORAGE_FOLDER
		# tree $STORAGE_FOLDER
		cd $STORAGE_FOLDER ; find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"; cd - > /dev/null
	else
		echo "SPM storage does not exist!"
	fi
}

cmd_enc(){
	if [[ -d $STORAGE_FOLDER ]]
	then
		if (( $# > 0 ))
		then
			if [[ -f "$STORAGE_FOLDER/$1" ]]
			then
				echo 'File already exists!'
			else
				mkdir -p "$(dirname "$STORAGE_FOLDER/$1")"
				touch "$STORAGE_FOLDER/$1.tmp"
				nano "$STORAGE_FOLDER/$1.tmp"
				gpg -c -a -o "$STORAGE_FOLDER/$1" "$STORAGE_FOLDER/$1.tmp" && rm "$STORAGE_FOLDER/$1.tmp"
			fi
		else
			echo "No encryption file specified!"
		fi
	else
		echo "SPM storage does not exist!"
	fi
}

cmd_dec(){
	if [[ -d $STORAGE_FOLDER ]]
	then
		if [ -f "$STORAGE_FOLDER/$1" ]
		then
			gpg -d --no-symkey-cache "$STORAGE_FOLDER/$1"
		else
			echo "No decryption file specified!"
		fi
	else
		echo "SPM storage does not exist!"
	fi
}

cmd_rm(){
	if [[ -d $STORAGE_FOLDER ]]
	then
		if [ -f "$STORAGE_FOLDER/$1" ]
		then
			read -r -p "Are you sure? [y/N] " flag
			flag=${flag:-N}
			if [ $flag = "y" -o $flag = "Y" ]
			then
				rm "$STORAGE_FOLDER/$1"
				echo "$1 removed"
			fi
		else
			echo "File does not exist or not specified!"
		fi
	else
		echo "SPM storage does not exist!"
	fi
}

cmd_edit(){
	if [[ -d $STORAGE_FOLDER ]]
	then
		if [ -f "$STORAGE_FOLDER/$1" ]
		then
			gpg -d --no-symkey-cache -o "$STORAGE_FOLDER/$1.tmp" "$STORAGE_FOLDER/$1"
			nano "$STORAGE_FOLDER/$1.tmp"
			rm "$STORAGE_FOLDER/$1"
			gpg -c -a -o "$STORAGE_FOLDER/$1" "$STORAGE_FOLDER/$1.tmp" && rm "$STORAGE_FOLDER/$1.tmp"
		else
			echo "File does not exist or not specified!"
		fi
	else
		echo "SPM storage does not exist!"
	fi
}

cmd_ver(){
	echo "$VERSION"
}

case "$1" in
	help|--help|-h) cmd_help ;;
	init) cmd_init ;;
	ls) cmd_ls ;;
	enc) shift; cmd_enc "$@" ;;
	dec) shift; cmd_dec "$@" ;;
	rm) shift; cmd_rm "$@" ;;
	edit) shift; cmd_edit "$@" ;;
	version) cmd_ver ;;
esac

exit 0